version: "3.7"

services:
  app:
    build: ./app
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    command: npm start